config/routes.rb
Rails.application.routes.draw do
  resources :toys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
  end

  def new
    @toy = Toy.new
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      # 成功
      redirect_to toys_path, notice: "上傳資料成功!"
    else
      # 失敗
      render :new
    end
  end

  def edit
    @toy = Toy.find_by(id: params[:id])
    if @toy.update(toy_params)
      # 成功
      redirect_to toys_path, notice: "更新資料成功!"
    else
      # 失敗
      render :edit
    end
  end

  def destroy
    @toy = Toy.find_by(id: params[:id])
    @toy.destroy if @toy
    redirect_to toys_path, notice: "資料已刪除!"
  end

  private
  def toy_params
    params.require(:toy).permit(:name, :time, :number, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toys</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toys/_form.html.erb
<%= form_for(toy) do |f| %>
  <div class="form-style">
    <%= f.label :name %>
    <%= f.text_field :name %>
  <br>
  </div>

  <div class="form-style">
    <%= f.label :time %>
    <%= f.datetime_local_field :time %>
  <br>
  </div>

  <div class="form-style">
    <%= f.label :number %>
    <%= f.number_field :number %>
  <br>
  </div>

  <div class="form-style">
    <%= f.label :description %>
    <%= f.text_area :description %>
  <br>
  </div>

  <%= f.submit "送出"%>
<% end %>

app/views/toys/edit.html.erb
<h1>編輯表單</h1>
<%= render "form", toy: @toy %>
<br />
<%= link_to '回列表', toys_path %>

app/views/toys/index.html.erb
<h1>玩具列表</h1>
<%= link_to "新增玩具" , new_toy_path %>
<table>
  <thead>
    <tr>
      <th>玩具名稱</th>
      <th>上傳時間 </th>
      <th>數量</th>
      <th>說明</th>
      <th>修改</th>
    </tr>
  </thead>
  <tbody>
    <% @toys.each do |toy| %>
      <tr>
        <td><%= toy.name %></td>
        <td><%= toy.time %></td>
        <td><%= toy.number %></td>
        <td><%= toy.description %></td>
        <td>
          <%= link_to "編輯" , edit_toy_path(toy) %>
          <%= link_to "刪除", toy_path(toy), method: "delete", data: { confirm: "確認刪除" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/toys/new.html.erb
<h1>新增表單</h1>
<%= render "form", toy: @toy %>
<br />
<%= link_to '回列表', toys_path %>